replicaCount: 1

appPort: 5000

image:
  registry: 431628235125.dkr.ecr.us-east-1.amazonaws.com/parking-devops-api
  tag: latest

environmentVariables:
  - name: FLASK_DEBUG
    value: development

environmentVariablesFrom:
  - secretRef:
      name: mongodb-credentials

livenessProbe:
  httpGet:
    path: /health
    port: 5000
readinessProbe:
  httpGet:
    path: /health
    port: 5000

ingress:
  enabled: false

mongo:
  database: AgAkagGNhFVuoopOxcW3sQBE/c4bBoJjpcrdtiSChAaZ8a332fUe8wUQjyZoiYbETwr34GH4Lh34b14YLeAt5LGvpOGB19m/mk5MJgDryfHe9DcnLaeUB0HdrVP2oSPp2cMmgzYnhylAAN+zqHAodGLzrqMNccPOydPryNQd7oy0+anysZNmbi8tz9QhgZzUh1IeE0l5f43yZm7ZmHxrL1DdIT8JejPzukkOJN2X0d7stMmj+LXjpECFFXI0e7x6D92VrnrjV1zKRVtwUz1cQYPtagI/igTwm0qq/y1KXwOQ+9YvzdI4nbtyMpJbT7shInJxNyy6gCUieTB84hQ6ka6wtsGTN1PeONVgH0h8evU1OsgmSavUG1Q46n67T8KR8IE1dOO56ehPaqbydJ91SaETOdRuKKR0OCCPI+BMRC2HwurZJvAZjPHKc4HPCdrH2LWUj7YLCiF6XR2V6j7rpCp7WeQXBmAJeUU6lvb5KP1FUcJjmaAQBp05yTmHgP267jLOOKfo4gIt+2v/wvVXssC+ohJTNeME23HJ6JDWsPw3D6x5eoVYlFKp+gvotvSuPmeNm8SdrTYZy7kvV62bZXBkZDuh0BSG6bNR2YqMMlmYbZj09O8i30xewojGBuZvyF7v7PU2gLl55mj4IXp1wD3q23VRFZ0Kfigvu59U6Yu3Tufto/cLEJEUxOI0gIIesmD+zPQOP0ieIPI=
  host: AgDJdREUMx95WLsN097jtfuBwSOilgTVhWJLeDrpHdcojh3O0/7XoajuYID8pQvMlc7W3MC56cDm9rdZhTexPowopgD3mYy2TaMbbNO9ykIc5bKVb5bw3giLR2DgkN9AN77/DcUmSZELZqdq/pWTHJ2H19VHtkIlyWI3g+mdsQ5ZmJf9rNVnMBv9rzIuHJXRhYwvTGKCopJuQxbxIjHQq6l8GymQrOExfUtUnu4hJlvg3feUhI2XCz2QfTMjIwYNHNRIy1YEChe5ydY/9CTPj1jlhuR2/Ahn428qgYAapi+G9pAOf9boGmFX+CzKYfMbrog7Kx1QT/bgtreOFk8ScbPtuJmzygbJWIruMRVLAH/tFOt0OFQUO0jeMaSGxCTHGJVF9Zoci0aU23o+t7WT00FIF4Gh5HhVuccCrgT/Az1MnO2dT8VbxHRPBCOE2xpCpIT7PiHUGRWP/oGWjeT5ZhOJ2xJvbwxjU3fAA5UOneyy5uym7hEc5YhHXjeBGP/63xwdtvdL+vxq18GAU7MiAwz2ftCC5fK2ehgEyg4Kc/Qy2H6wRfu2YmapZ6DcunCt0m34E8UKTUcmLq2d8b9jYHbhUJzPDQSQ+a9E/amZSlkEKj1OqyldZvLAs+c4n+q/AG8MUBO5K4s48maFypi6lpSkSoZ/F/Ps3r8FALidgFdm87dh3yDIzHL39sGAmNAOgmbIdfT9kF9H85sEiVjTkkl2NKg=
  password: AgCOxQQP7hYg2HyaZjjXl3PcgfC8pwAJxMfaI02HvO4KdZf99a2Tnh+KNEAMHUbuSNsE+qtFCA8JYVBAdj5IwCyxBF4tRGcYqghXjRsMsBLZh0CdK60eirKJ4MZrVCWK8EcTjynEDtaLxT1EFKmAezDOn4NTRyCFoGLWF0lx3zw90cUIUxgcy70jsCUq3NfPaw80XDp7MXBseGahn2NIT8YrnbAqSo2proj6nmj1ZKDD0XWiZZHAs5H3v39LMj+RQQYGjbZk3oOMgQYIQPKGoigysv+VgadT1UelyAOMdulsjoZRy1RPMcECSOyabeJ14blMsMZ07c3mi0sHbugjsm9wsXtWFgatJ3mOjCzQriEIoQ2DLD0z4RnU+kvQz3d3RZuBtxJY27fuIGQFlLB1xh4CKoU2QuO0MOsHt2gVXtbZhmEF+waz7PtlULjltA8ATuINh4aSFtsA5Jmo/JRVK1LKMuTHLMZb9oSUqWJMU5Jh37yiITzu8B7DyePufhU5TT38TrbLrkuyhibUngoF9pPVSiy1EMIEf/bRjBhhdJydUezNUnUBzN4RzYfeLdNkfzcoMuQeH8sMh9KuLGxMHzrwF/xRfQZZybislRl5hsrV4BFx7j13DuRddjVccElIJzS7nTviYpfhoLW0je0NYA/lC9bOmE0AUovnVI6bvKlPpyHRWUANZ7CFODrbIzBmsfa8hUkl
  user: AgBxMHIOLzjVX9U2enkUQE04xCfXbmEtYx4KSEKPkAzg34HoSyaByt/Sg+F69MzSaBu/NZphvc2yuKVIFxmocC7mXF1fYGnAQozpj2Y/PLy39nZnn366IY2AzzByCKcGWxQmTsKanH0HHDI8Sy0wkUih0q9sTuKrYnLouNLVljPkcKEvuWPRGl5Ko6JMcQVVOXFuNYYBmupsrk6lBG4HEYMnSjGadoc/CAWKzWH6I3ujuiGXvV2edUYagj+8Nkq2XW+bosQLm7Kxzea1mLgSmo73IDseYlxYfx3PhoYsqhyWe8QCotVRr84dv83NxNbtF+icRdj1eGzpw0Rf1qzxgR4OI4OqM/TG3JUTbpWapyvDhuTqhPZoJZXBHQvD7sylge1lEQdzHCTBnnz7zIVzadIfOlAuGOqF4eS9bd4vd7tTMLSHO4W4P7vbiiGLvNhrA6TfoLwGi6rtTi1DkxREFxROgk+26+oPUyL4oIGXUt86kmRuL+Lssot0k60EMHRBovCS6jqeHot42+KmjReDsQmrS14DQPaMG1x+gszFgR4wr7c7FMHjT5b9iUqRK2pX+bmsZHGd2S0G5xWlvDJKsN2z2ZajZGdbk92m2X+eMRtfoerksqfTVCboNpi9kbdXmDFuEA56IUoWeT1m/Vt2gHmAhrvmQ53Z6oPAEAuqJV26tJHQcZ29Hjp6ut8qJcLG22fEIpOM