version: '3.9'

services:
  mongodb:
    image: mongo
    container_name: mongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root

  api:
    build:
      context: .
    ports:
      - 5000:5000
    restart: always
    volumes:
      - .:/app
    depends_on:
      - mongodb