version: '3.9'

services:
  db:
    image: postgres:alpine3.18
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: parkingdb

  api:
    build:
      context: .
    ports:
      - 5000:5000
    restart: always
    volumes:
      - .:/app
    depends_on:
      - db