---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: mongodb-credentials
  namespace: default
spec:
  encryptedData:
    MONGODB_DB: {{ .Values.mongo.database }}
    MONGODB_HOST: {{ .Values.mongo.host }}
    MONGODB_PASSWORD: {{ .Values.mongo.password }}
    MONGODB_USER: {{ .Values.mongo.user }}
  template:
    metadata:
      creationTimestamp: null
      name: mongodb-credentials
      namespace: default
