apiVersion: v1
kind: Service
metadata:
  labels: {{ include "parking-devops-api.labels" . | nindent 4 }}
  name: {{ include "parking-devops-api.fullname" . }}
spec:
  ports:
  - port: {{ .Values.appPort | default 5000 }}
    protocol: TCP
    targetPort: {{ .Values.appPort | default 5000 }}
  selector:
    app: {{ include "parking-devops-api.fullname" . }}
