
Vagrant.configure("2") do |config|
  config.vm.box = "generic/ubuntu2004"
  config.vm.network "private_network", ip: "192.168.56.5"

  config.ssh.insert_key = false
  config.ssh.private_key_path = ['~/.vagrant.d/insecure_private_key', '~/.ssh/vagrant_id_rsa']
  config.vm.provision "file", source: "~/.ssh/vagrant_id_rsa.pub", destination: "~/.ssh/authorized_keys"
end
